In [1]:
import sys
sys.path.insert(1, '/Users/Andrew/Documents/PhD/Scripts/Python/pygplates_rev13')
import pygplates
import numpy as np
import pandas as pd
import pickle
import matplotlib
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype'] = 42
%matplotlib inline

In [32]:
#set path to rotation file, shapes etc.
basedir = '/Users/Andrew/Documents/PhD/Models/1000-410_Models'
basedir2 = '/Users/Andrew/Documents/PhD/Manuscripts'


input_rotation_model_1000_500 = '%s/Topos_for_plotting/1000-410_rotations(finished)_20170621a_north_china-tarim-aus.rot' % basedir
input_rotation_model_500_410 = '/Users/Andrew/Documents/PhD/Models/Domeier_models/Merge/Domeier-EarlyP-merge-Rotation_ASM.rot'

input_rifts = '%s/Rifts/Rifts.gpml' % basedir
input_rifts_with_failed_rifts = '%s/Rifts/Rifts_with_failed_rifts.gpml' % basedir
input_rifts_modelled_additions = '%s/Rifts/Rifts_with_modelled_additions.gpml' % basedir
input_rifts_with_modelled_additions_failed_rifts = '%s/Rifts/Rifts_with_modelled_additions_failed_rifts.gpml' % basedir
input_rifts_with_modelled_additions_failed_rifts_PZ = '%s/Rifts/Rifts_with_modelled_additions_failed_rifts_PZ.gpml' % basedir

rotation_model_1000_500 = pygplates.RotationModel(input_rotation_model_1000_500)
rotation_model_500_410 = pygplates.RotationModel(input_rotation_model_500_410)

rifts = pygplates.FeatureCollection(input_rifts)
rifts_with_failed_rifts = pygplates.FeatureCollection(input_rifts_with_failed_rifts)
rifts_with_modelled_additions = pygplates.FeatureCollection(input_rifts_modelled_additions)
rifts_with_modelled_additions_failed_rifts = pygplates.FeatureCollection(input_rifts_with_modelled_additions_failed_rifts)
rifts_with_modelled_additions_failed_rifts_PZ = pygplates.FeatureCollection(input_rifts_with_modelled_additions_failed_rifts_PZ)

palaeozoic_rifts = pd.read_csv('%s/Merdith_Rifting_length/450-0_Rifting_length/Sengor_RiftLengthBinned.csv' % basedir2, header=None)


In [33]:
for i in rifts_with_modelled_additions_failed_rifts:
    print i.get_name(), i.get_reconstruction_plate_id(), i.get_valid_time()
    tmp = i.get_geometry()
    print tmp.to_lat_lon_array()
    rift_length = i.get_geometry().get_arc_length()
    individual_rift_length_kms = rift_length * pygplates.Earth.mean_radius_in_kms
    print individual_rift_length_kms

R1a 2204 (1000.0, 570.0)
[[-15.23178965 -39.73231231]
 [-22.42681783 -44.24315272]]
930.080459004
R2a 7701 (880.0, 550.0)
[[-19.32022102  22.0683239 ]
 [-15.49294014  28.97322302]]
847.080143175
R8 2204 (850.0, 650.0)
[[-21.46299997 -46.86807232]
 [-11.98549208 -49.10406917]]
1080.34175923
R7 2201 (700.0, 540.0)
[[-22.04626679 -61.16677801]
 [-14.10827072 -52.76418163]]
1251.48291247
R6 2201 (850.0, 540.0)
[[ -3.83845038 -48.07095557]
 [ -5.92395901 -48.58396354]
 [ -9.13609144 -49.88134619]
 [-15.00303486 -53.06104354]]
1361.74942265
R5a 1001 (830.0, 520.0)
[[  70.01147756 -134.41017714]
 [  56.35241111 -119.57710519]
 [  48.02210892 -113.16354576]
 [  42.75120012 -115.53126579]
 [  37.48126772 -115.35294907]]
3904.59166997
R2c 7701 (760.0, 550.0)
[[-16.25104239  24.84070089]
 [-19.71809745  22.36263611]
 [-23.85943588  14.0278747 ]]
1441.83674322
R4 7703 (850.0, 640.0)
[[  6.22358592 -10.70850719]
 [  7.88964363 -12.41416582]
 [ 10.45840506 -13.50002138]]
573.597558677
R9c 3001 (615.